security:
  encoders:
    App\Entity\User:
      algorithm: auto

  # https://symfony.com/doc/current/security/experimental_authenticators.html
  enable_authenticator_manager: true
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    login:
      user_checker: App\Security\UserEnabledChecker
      pattern: ^/api/login
      stateless: true
      json_login:
        username_path: email
        check_path: /api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  role_hierarchy:
    ROLE_PROPERTY_OWNER:
      [
        ROLE_SELLER,
        ROLL_BUYER,
        ROLE_LANDLORD,
        ROLE_COMMENTER,
        ROLE_MESSENGER,
        ROLE_RATER,
      ]
    ROLE_TENANT: [ROLE_COMMENTER, ROLE_MESSENGER, ROLE_RATER]
    ROLE_AGENT: [ROLE_PROXY_LANDLORD, ROLE_PROXY_SELLER]
    ROLE_SERVICE_PROVIDER: [ROLE_MESSENGER, ROLE_MESSENGER]

  access_control:
    - { path: ^/api/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/users, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
