twig:
    globals:
        regional: '@App\Service\RegionalSettingsService\RegionalSettingsService'
    form_themes:
         - 'bootstrap_5_layout.html.twig'
         - '@TbbcMoney/Form/fields.html.twig'

    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
