version: "3.4"

services:
  php:
    image: ghcr.io/residewise/php:main
    volumes:
      - .:/app
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - database

  caddy:
    image: ghcr.io/residewise/caddy:main
    depends_on:
      - php
    environment:
      SERVER_NAME: localhost, caddy:80
      MERCURE_PUBLISHER_JWT_KEY: secret
      MERCURE_SUBSCRIBER_JWT_KEY: secret
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
      - ./public:/app/public
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp

  js-watch:
    image: node:14
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: [""]
    command: "bash -c 'yarn install && yarn run watch'"

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: residewise
      POSTGRES_PASSWORD: residewise
      POSTGRES_USER: residewise
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer:4.8.0
    ports:
      - "8000:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      - database

volumes:
  php_socket:
  caddy_data:
  caddy_config:
